### ISSUE TITLE
estGaussianAmplitude3D function missing

### ISSUE THREAD

**Issue by kl943112771** [francois-a/llsmtools#1]
![wechat image_20181002144758](https://user-images.githubusercontent.com/43711578/46376102-62159680-c652-11e8-894f-5a0622cb69d7.jpg)

When I running cmeAnalysis3D, it was showing me that I missed a function called estGaussianAmplitude3D, and couldn't find it anywhere. Can anyone please help.

**Comment by francois-a** [comment]
I've added the file: 826a4fb8bc99d925d5746303d289836a2c780bde. Thanks for pointing this out.

**Comment by kl943112771** [comment]
Thank you so much.
